export const environment = {
  production: false,
  idmClientId: 'a923e57545d24804a804973731c38747',
  clientId: '1QIwuXglQ0xImRhjTUbJ7k6x7AR6MibG',
  ruId: '1d18eecc-6f4e-476f-bec3-f2c2c94521f6',
  idmLoginURL: "https://ry1drvemksr1.mof.gov.sa:50301/irj/servlet/prt/portal/prtroot/pcd!3aportal_content!2fmof.gov.sa.f_mof_base!2fmof.gov.sa.f_iviews!2fmof.gov.sa.i_auction",
  idmLogoutUrl: "https://ry1drvemksr1.mof.gov.sa/sap/public/bc/icf/logoff?sap-client=100",
  idmHomeUrl: "https://10.14.8.61:8055",
  apiAuctionURL : "/internal/v1/e-auction/auctions",
  apiFilenetURL : "/internal/v1/e-auction/files",
  apiCommiteeURL : "/internal/v1/e-auction/committees",
  apiBidderFinalInvoiceURL : "/mock-internal/auctions/1/final-invoice",
  apiBidderAuctions : "https://10.13.85.56:9443/internal/v1/e-auction/e-bidder/bidders",
  apiBidderBidAuctions : "/sap/opu/odata/sap/ZSRM_PREAUCTION_APPROVAL_SRV/PreAuctionListSet",
  apiBidderParticipationAuctions : "/sap/opu/odata/sap/ZSRM_PREAUCTION_APPROVAL_SRV/BidderParticipationSet",
};  